# Generated by Django 3.2.9 on 2021-11-13 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_persona')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='contrasena')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id_predio', models.CharField(max_length=156, primary_key=True, serialize=False, unique=True, verbose_name='matricula_inmobiliaria')),
                ('cedula_catastral', models.CharField(max_length=156, unique=True, verbose_name='Cedula_catastral')),
                ('direccion', models.CharField(max_length=130, verbose_name='dirección')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_predio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_predio', models.CharField(max_length=30, verbose_name='tipo_predio')),
                ('direccion', models.CharField(max_length=130, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_user', models.CharField(max_length=30, verbose_name='tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('id_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_inmobiliaria', to='authApp.predios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='predios',
            name='type_predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='authApp.tipo_predio'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipe_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='authApp.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
